language: bash
services:
  - docker
env:
  - STACK=heroku-16 POSTGRESQL_VERSION=9.6
  - STACK=heroku-16 POSTGRESQL_VERSION=10
  - STACK=heroku-16 POSTGRESQL_VERSION=11
  - STACK=heroku-16 POSTGRESQL_VERSION=12
  - STACK=heroku-16 POSTGRESQL_VERSION=13

  - STACK=heroku-18 POSTGRESQL_VERSION=9.6
  - STACK=heroku-18 POSTGRESQL_VERSION=10
  - STACK=heroku-18 POSTGRESQL_VERSION=11
  - STACK=heroku-18 POSTGRESQL_VERSION=12
  - STACK=heroku-18 POSTGRESQL_VERSION=13

  - STACK=heroku-20 POSTGRESQL_VERSION=9.6
  - STACK=heroku-20 POSTGRESQL_VERSION=10
  - STACK=heroku-20 POSTGRESQL_VERSION=11
  - STACK=heroku-20 POSTGRESQL_VERSION=12
  - STACK=heroku-20 POSTGRESQL_VERSION=13

  # Test relying on the buildpack's default PostgreSQL version.
  - STACK=heroku-18

  # Test specifying an exact point release version.
  - STACK=heroku-18 POSTGRESQL_VERSION=11.7
script:
  - ./support/test.sh "${STACK}"
